
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 16 22:24:34 VET 2010
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MASMAS = 47;
  public static final int DOSPUNTOS = 46;
  public static final int DIVIDE = 5;
  public static final int MENOSMENOS = 49;
  public static final int CHAR = 27;
  public static final int UMINUS = 7;
  public static final int ENTERO = 61;
  public static final int O = 37;
  public static final int CASE = 16;
  public static final int DIFERENTE = 34;
  public static final int LPAREN = 8;
  public static final int I = 36;
  public static final int LCORCHETE = 22;
  public static final int FOR = 59;
  public static final int REF = 52;
  public static final int MINUS = 3;
  public static final int RPAREN = 9;
  public static final int MENORIGUAL = 31;
  public static final int ELSEIF = 13;
  public static final int IGUAL = 11;
  public static final int LLLAVE = 20;
  public static final int MASIGUAL = 48;
  public static final int IN = 53;
  public static final int BOOL = 28;
  public static final int OO = 38;
  public static final int II = 35;
  public static final int RLLAVE = 21;
  public static final int PLUS = 2;
  public static final int MAIN = 10;
  public static final int IF = 12;
  public static final int ID = 54;
  public static final int MAYORIGUAL = 33;
  public static final int EOF = 0;
  public static final int RETURN = 24;
  public static final int TRUE = 40;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int NEGACION = 39;
  public static final int MENOR = 30;
  public static final int MOD = 6;
  public static final int BREAK = 43;
  public static final int TKSTRING = 55;
  public static final int VOID = 25;
  public static final int SWITCH = 15;
  public static final int MAYOR = 32;
  public static final int TIMES = 4;
  public static final int FOREACH = 18;
  public static final int TKFLOAT = 57;
  public static final int ELSE = 14;
  public static final int PUNTO = 51;
  public static final int IGUALIGUAL = 19;
  public static final int WHILE = 58;
  public static final int DEFAULT = 17;
  public static final int RCORCHETE = 23;
  public static final int FLOAT = 29;
  public static final int MENOSIGUAL = 50;
  public static final int STRING = 26;
  public static final int FALSE = 41;
  public static final int STRUCT = 60;
  public static final int TKENTERO = 56;
  public static final int SUB = 42;
  public static final int PYC = 44;
}

